"""PalmX-style compatibility wrapper.

The buyer KB CSV is generated by the acquisition-only builder. This phase does
not generate personas, intents, recommendation rules, dashboards, frontend code,
or AI chat behavior.
"""

from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "build_csv.mjs"


if __name__ == "__main__":
    try:
        raise SystemExit(subprocess.call(["node", str(SCRIPT)], cwd=ROOT.parent))
    except FileNotFoundError:
        print("Node.js is required to run the Aqaar KB-Acq builder.", file=sys.stderr)
        raise SystemExit(127)
